### ISSUE TITLE
WDS trainer & student guides

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [Microsoft/MCW-Big-Compute#2] opened 2018-07-17 18:34 UTC
-  Data Loading - student guide asks 2 questions, trainer guide, preferred solution only answers # 1.
 -  Batch Computing - student guide lists 6 questions, trainer guide, preferred solution answers 10 (and the questions are different).
 -  Visualization & Remote Workstations - Student guide has questions 1 & 2, but trainer guide, preferred solution answers 1 - 6.

*Please make sure whatever changes you make in guides match what's in the PPT as well.

**Comment by ZoinerTejada** [comment] 2018-08-01 00:32
These have been addressed by commit 596a504.  

**Data Loading** 
That's by design, the second question is a prompt for them to update their design which is already covered in the preferred solution high-level architecture and would be redundant here.

**Batch Computing**
The questions have been aligned to the trainer guide solution.

**Visualization & Remote Workstations**
The questions have been aligned to the trainer guide solution.

**Closed by ZoinerTejada** 2018-08-01 00:32 UTC
